<a href="https://colab.research.google.com/github/XAEA-16/CodeSmashers/blob/Wordpress2/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:

t = turtle.Turtle()
s= turtle.Screen()

s.bgcolor('black')
t.width(2)
t.speed(15)

col=('yellow','green','red','blue')
for i in range (300):
    t.pencolor(col[i%4])
    t.forward(i*4)
    t.right(137)

In [ ]:
a=[]
for _ in range(int(input())):
    name = input()
    score = float(input())
    a.append(name)
    a.append(score)
    
    c=set(a)
    c=list(c)
        
        

   


3
rahul
45


TypeError: ignored

In [ ]:
2
2
d2233d3
23namemarks("rahul",32)
 a=[]



IndentationError: ignored

In [ ]:
25a
file = open("vita.txt","r")
nlines=0
nwords=0
wset=set()
for line in file:
  words=line.split()
  nlines+=1
  nwords+=len(words)
  wset=set(words)
file.close()
print("lines:",nlines,"words:",nwords,"the unique words are ",wset)

In [ ]:
def TotalTax(amt,tax=8,GStax=5):
  def GST(finalamount,GStax):
    total1=finalamount*(GStax/100)
    total1+=finalamount
    return print("total amount is:",total1)
    
  total=amt*(tax/100)
  total+=amt
  GST(total,GStax)

In [ ]:
TotalTax(1000)

total amount is: 1134.0


In [ ]:
a=[212,21,212,21,3232,323212]

print(len(a))
b=set(a)
for c in a:
 c= count(a)
 c
 print(c)

6


NameError: ignored

In [ ]:
while True:
  a=  (input())
  if a=="":
    break
    int (a)
    b= count(a)
    print(b)


In [ ]:
import cmath

a=1
b=2
c=1


d= (b**2)-(4*a*c)

sol_1= (-b-cmath.sqrt(d)/(2*a))
sol_2 = (-b+cmath.sqrt(d)/(2*a))


print('The sol are in the format {0},{1}'.format(sol_1 , sol_2))

In [ ]:
n=int(input("enter value"))
nn=n
totalk=n+nn+nn
print(totalk)

In [ ]:
n=int(input('Enter Number : '))
print("After computing : ",n+((n*10)+n)+((n*100)+(n*10)+n))

In [ ]:
osum=0
b=int(input("enter the range"))
for i in range(0,b):
  a=int(input(" how many numbers you want"))
  if a<0 :
   break
  osum+=a

print(osum)


In [ ]:
amt=10000;intr= 3.5; year=7
p = 351000**7
print(p)

In [ ]:
a=int (input("no 1"))
b=int (input("no 2"))
c=int (input("no 3"))
tot=a+b+c
if a==b==c:
  print(tot**3)
else:
  print(tot)


In [ ]:
r=6

sphere=(4.18*(r**3))
print(sphere)

In [ ]:
d =[]
while True:
  data=int(input()) 
  if data<0:
    break
  d.append(data)i 

      
 

In [ ]:
feet = float (input("Enter the number"))

inches=feet*12
yards= feet*0.33
miles= feet* 0.00189

print(inches,"inches",yards,"yards", miles,"miles")

In [ ]:
x=int (input(" enter x:"))
y= int (input(" enter y:"))

y=(x+y)**2
print(y)

In [ ]:
amt=10000
intr=3.5
yr=7

ci = 10000(1+35)

In [ ]:
import numpy as np
np.pv(3.5,10000,7)



In [ ]:
l=[1,5,3,8]
n=int(input("Enter the number"))
if l.count(n)==True:
  print("True")
else:
  print("False")


In [ ]:
Lasa=[] 
abc=()
abc.
while True:
 data =input("enter data")
 

In [ ]:
thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

In [ ]:
n=int (input())

temp=str (n)
t1=temp+temp
t2=temp+temp+temp
comp =n+int (t1)+int (t2)
print(comp)

In [ ]:
n=int (input())

temp=str (n)
print(temp)
t1= temp+temp
print(t1)

In [ ]:
l=[12,4,4,4,412]
d=l


print(" count of 4 ",l.count(32))

In [ ]:
l=[12,2112,121,12,12]
n=int(input(" enter thr num "))
if l.count(n,2)==True:
  print("present")
else:
  print(" not present")


In [ ]:
L=[12,121,12121,1212121]
l3=[121212,21,12,1212]
l=set (L)
l
LL=set (l3)
LL
type (l)


In [ ]:
l1=[1,3,5,7,9]
l2=[1,2,4,6,7,8]
l3=set (l1)
l5=set (l2)
l9=(l3.difference(l5))|(l5.difference(l3))
print(l9)

In [ ]:
dit={1:22,2:33,3:66}
sum=0
for i in dit.values():
  sum+=sum+i
print(sum)

In [ ]:
n=int (input())

temp=str (n)
t1=temp+temp
t2=temp+temp+temp
comp =n+int (t1)+int (t2)
print(comp)

In [ ]:
dic={1:"rahul",2:"bagal",3:"randwa"}

for i in dic.clear():
  print(dic)

In [ ]:
list1=[(2,5),]

In [ ]:
amt=10000
it=3.5
y=7
Fv=amt*((1+(0.01*it)) ** y) # FV=P((1+r)^t)
print("Future Value:",Fv)

1. Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a
given list of non-empty tuples.
Sample List : [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
Expected Result : [(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]

2. Write a Python program to get the difference between the two lists.
list1 = [1, 3, 5, 7, 9]
list2 = [1, 2, 4, 6, 7, 8]
O/P
[9, 3, 5, 8, 2, 4, 6]

In [ ]:
l1 =[1,3,5,7,9]
l2 = [1, 2, 4, 6, 7, 8]
a=set (l1)
b=set (l2)
d=a - b
e= b - a
f=list (d)
f
g=list (e)
g
h = f + g
print(h)


3. Write a Python program to find the second smallest number in a list.
EXAMPLE
[1, 2, -8, -2, 3]
O/P
-2

In [ ]:
l1 = [1,2,-8,-2,3]
l2=sorted(l1)
#  it will sorted the list
print(l2)
# for smallest
print(l2[1]) 
# this will give you smallest number 



4. Write a Python program to find the second smallest number in a list. [2,4,3,5,7]

In [ ]:
l1= [2,4,3,5,7]
l2=sorted(l1)
print(l2)
print(l2[1])

5. Write a Python script to concatenate following dictionaries to create a new one.
Sample Dictionary :
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

In [ ]:
dic1={1:10, 2:20} 
dic2={3:30, 4:40}
dic3={5:50,6:60}

dict4={}
dict4.update(dic1)
dict4.update(dic2)
dict4.update(dic3)
print(dict4) 
dict6={}
# copy will overwrite the element and hence the old values get changes hence we canot use copy to add dict
# dict6=dic1.copy() 
# dict6=dic2.copy()

dict6


6. Write a Python program to sum all the items in a dictionary.

In [ ]:
newitems={1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}
valuess=newitems.values()
valuesss=sum(valuess)
print(valuesss)



7. Write a Python program to split a list every Nth element.
Sample list: [&#39;a&#39;, &#39;b&#39;, &#39;c&#39;, &#39;d&#39;, &#39;e&#39;, &#39;f&#39;, &#39;g&#39;, &#39;h&#39;, &#39;i&#39;, &#39;j&#39;, &#39;k&#39;, &#39;l&#39;, &#39;m&#39;, &#39;n&#39;]
Expected Output: [[&#39;a&#39;, &#39;d&#39;, &#39;g&#39;, &#39;j&#39;, &#39;m&#39;], [&#39;b&#39;, &#39;e&#39;, &#39;h&#39;, &#39;k&#39;, &#39;n&#39;], [&#39;c&#39;, &#39;f&#39;, &#39;i&#39;, &#39;l&#39;]]

In [ ]:
lst = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']
s = []
n = int (input("enter number"))
for x in range(n):
    s.append(lst[x::n])

print(s)

9. Write a Python program to remove duplicates from a list of lists.
Sample list : [[10, 20], [40], [30, 56, 25], [10, 20], [33], [40]]
New List : [[10, 20], [30, 56, 25], [33], [40]]


In [ ]:
l1=[[10, 20], [40], [30, 56, 25], [10, 20], [33], [40]] 

res = []
for i in l1:
    if i not in res:
        res.append(i)


print(res)

In [ ]:
def nokia(*s):
  print(s)


nokia("sdas","dasd","dasdas",dasda)


In [ ]:
def  info(name="rahul",native="duniya",sex="asd"):
  print(" my name is ",name,"i am from ",native,"i have a habit of doing",sex)




info("rahul","",)

In [ ]:
def val(n):
  print(n+2323)


  
val(23)

In [ ]:
def suma(n1,n2):
  print(n1+n2)


suma("das","gas")

In [ ]:
def __str__(self):
  return

In [ ]:
def details():
    print("hi there my name is rahu")


def sex():
  print(" unfortunately still a vargin ")

details()
sex()


In [ ]:
class bank:
     
  account_detals={}

  def __init__():
    account_detals=acc_id

 def details(self,name):
     self.name=name
     acc_id=print(id(self))
  

 def info(self,name):
     self.name=name
     print("seen you after long time")
     print(" hi "+self.name +" how are you"+" your account number is"
     )
     print(id(self))
 
 def accountid(self):
   consumers=()
   consumers.a

    

 def balance(self):
  
     self.balance= float ( input(" enter amt")) 
     
     print(" apke pass ithna paisa hee " + str (self.balance))
  
 def deposite(self):
  
     self.deposite= float ( input(" enter amt"))
     self.balance+= self.deposite
     print(" apke pass ithna paisa hee" + str (self.balance))  

 def withdraw(self):
     self.withdraw= float ( input(" enter amt to withdraw"))
     if self.withdraw > self.balance:
       print(" paisa kamao aur samjhe fir nikalna ")
     else:
         self.balance=self.balance - self.withdraw
         print(" the amount avilable after withdraw"+str ( self.balance))



In [ ]:
b = bank()
customers=[]
name =input(" enter the name :")

b.info(name)
# i=int (input("balance press: 1 || deposite press : 2  || withdraw press : 3 "))
# i={1:b.balance,2:b.deposite }
b.balance()
b.deposite() 
b.withdraw()


In [ ]:
i = 12
d = 8.0
s = 'HackerRank '
i=float (i)
i=int (i+d)
d= d+d
f=input(str(" enter the string you need "))
s=s+f 
s

1. Given a number count the total number of digits in a number
For example: The number is 75869, so the output should be
Reverse the following list using for loop
list1 = [10, 20, 30, 40, 50]
Expected output:
50
40
30
20
10

In [ ]:
list1 = [10, 20, 30, 40, 50]

for i in list1:
  print(i)

2. Given 2 strings, s1 and s2, create a new string by appending s2 in the middle of s1
Expected Outcome:
appendMiddle("Chrisdem", IamNewString) → "ChrIamNewStringisdem"

In [ ]:
s1=("rahul")
s2=("group 26 ")

s1=s1+s2
s1

3. Arrange String characters such that lowercase letters should come first
Given input String of combination of the lower and upper case arrange characters in such a way that all
lowercase letters should come first.
Expected Output:
input_String = PyNaTive
arranging characters giving precedence to lowercase letters
aeiNPTvy
arranging characters giving precedence to lowercase letters:
yaivePNT

In [ ]:
inptStr=" PyNaTive "
dsfl=""
usfl=""
stdsup=""
lower_case=[]
upper_case=[]
for char in inptStr:
  if char.islower() :
    lower_case.append(char)
  if char.isupper():
    upper_case.append(char)



for i in lower_case:
  dsfl+=i
for i in upper_case:
  usfl+=i  

stdsup=strs+usfl
  
stdsup




4. Given a string, return the sum and average of the digits that appear in the string, ignoring all other
characters
For Example: –
sumAndAverage("English = 78 Science = 83 Math = 68 History = 65") = sum 294 Percentage is 73.5
Solution:

In [ ]:
import numpy as np

sumAndAverage=("English = 78 Science = 83 Math = 68 History = 65")
sums=[]
num=""
for i in sumAndAverage:
  if i.isdigit():
    sums.append(i)

 
 
print(sums)    




5. Given a two list. Create a third list by picking an odd-index element from the first list and even index
elements from second.
For Example:
listOne = [3, 6, 9, 12, 15, 18, 21]
listTwo = [4, 8, 12, 16, 20, 24, 28]
Expected Output:
Element at odd-index positions from list one
[6, 12, 18]
Element at even-index positions from list two
[4, 12, 20, 28]
Printing Final third list
[6, 12, 18, 4, 12, 20, 28]

In [ ]:
listOne = [3, 6, 9, 12, 15, 18, 21]
listTwo = [4, 8, 12, 16, 20, 24, 28]
l3=[]
l4=[]
for i in range(len(listOne)):
  if i%2!=0:
   l3.append(listOne[i])


l3


    # print(l3.append(listOne[i]))
# print(listOne[::])

# print(listOne[::-2])
# even number output 
print(l4.append(listTwo[::2]))
# l3

In [ ]:
listOne = [3, 6, 9, 12, 15, 18, 21]
listTwo = [4, 8, 12, 16, 20, 24, 28]
list3=[]

for i in range(len(listOne)):
  if i%2==1:
    list3.append(listOne[i])

for j in range(len(listTwo)):
  if j%2==0:
    list3.append(listTwo[j])    
print(list3)


listOne[1::2]

In [ ]:
heros=['spider man','thor','hulk','iron man','caption america']

len(heros)
heros.insert(5,'black panther')
len(heros)
heros.remove('black panther')
len(heros)
heros.insert(2,'black panther')
heros[1:3]=["doctor strange"]
heros

In [ ]:
rr=[]
n=int(input())
r=1
for i in range (0,n,1):
  if i%2!=0:
    
   print(rr.append(i))

rr   

In [ ]:
  
max = int(input("Enter max number: "))

odd_numbers = []

for i in range(max):
    if i%2 == 1:
        odd_numbers.append(i)

print("Odd numbers: ",odd_numbers)

In [ ]:
from google.colab import files
uploaded = files.upload()


In [ ]:
import pandas as pd
import io
df=pd.read_csv(io.BytesIO(uploaded['dara.xlsx']))
print(df)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import pandas as pd
import io
df=pd.read_csv(io.BytesIO(uploaded['mydata.csv']))
print(df)

In [ ]:
df.name


In [ ]:
df[['name','salary']]

In [ ]:
df

In [ ]:
df=['tax'] f[salary]*0.10

In [ ]:
dfflow=[df ['salary']<15000]

In [ ]:
dfflow 

In [ ]:
df.loc[1]

In [ ]:
for i in range (len(df)):
  print(df.loc[i])

In [ ]:
df['tax']=df['salary'                ]*0.1

In [ ]:
df

In [ ]:
import numpy as np


In [ ]:
m=np.arange(10,201,10).reshape(4,5)

In [ ]:
m

In [ ]:
m[1:2,3:3]

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([1,21,21,"rahul",True,False,False,True])

In [ ]:
s=s*2

In [ ]:
s

In [ ]:
s1= pd.Series([12,12,12])
s2=pd.Series([12,12])
s3=s1+s2


In [ ]:
s3

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import pandas as pd
import io
df= pd.read_csv(io.BytesIO(uploaded['rahul.csv']))
print(df)

In [ ]:
df.name

In [ ]:
df[["name","age","gender"]]

In [ ]:
df["loaction"]='([1,2],[12,21])'

In [ ]:
df

In [ ]:
dfflow=df['age']<26

In [ ]:
dfflow

In [ ]:
df.loc[0]

In [ ]:
for i in range(len(df)):
  print(df.loc[i])

In [ ]:
import numpy as np


In [ ]:
s=np.array([[1,2],[12,21,22],[23,23,23]])

In [ ]:
s.ndim

In [ ]:
r=np.array([[1,212],[2,12]])
r[[]]

In [ ]:
import pandas as pd
Mydf= pd.dataframe([])
Mydf([])

In [ ]:
import pandas as pd
Mydf= pd.Series()
Mydf

In [ ]:
import pandas as of
import io

In [ ]:
from google.colab import files
uploaded=files.upload()

In [ ]:
m=np.arange(1,11,1)

In [ ]:
m

In [ ]:
k=m.resize(2,5)

In [ ]:
q=np.arange(1,11,1)

In [ ]:
q

In [ ]:
p=q.reshape(2,5)

In [ ]:
p

In [ ]:
for row in p:
  for element in row:
    print(p)

In [ ]:
n= np.arange(10,100,10);

In [ ]:
n

In [ ]:
m=n.resize(3,3)

In [ ]:
m=n*2

In [ ]:
m

In [ ]:
for row in m :
  for element in row:
    print(element)

In [ ]:
m=np.arange(10,201,10).reshape(4,5)
m

In [ ]:
m[1:2,1:2]

In [ ]:
m[::,::-1]

In [ ]:
n=np.empty((2,3))
n

In [ ]:
from numpy import random

random.randint(10)
random.randint(10,size=(2,4))

In [ ]:
d=set()
while True :
  n=random.randint(1,20)
  d.add(n)
  if len(d)==9:
    break

print(d)
m=list(d)
p=np.array(m).reshape(3,3)
p

In [ ]:
import cv2
import sys


In [ ]:

cascPath = sys.argv[1]
faceCascade = cv2.CascadeClassifier(cascPath)

video_capture = cv2.VideoCapture(0)

while True:
    # Capture frame-by-frame
    ret, frame = video_capture.read()

    gray = cv2.cvtColor()

    faces = faceCascade.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(30, 30),
        flags=cv2.cv.CV_HAAR_SCALE_IMAGE
    )

    # Draw a rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # Display the resulting frame
    cv2.imshow('Video', frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
video_capture.release()
cv2.destroyAllWindows()

In [ ]:
x = int(input())
y = int(input())
z = int(input())
n = int(input())
   
s=x+y+z+n
i=1 
for i in s:
 x = [i for x in y for x in z ]
 y = [i for y in x for y in z]
 z = [i for z in x for z in y]
        
print(x,y,z)


In [ ]:
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
  
a=x
b=y
c=z
d=n
x,y,z,n=a,b,c,d
if a+b+c!=d:
 for a in (a,b,c):

   for b in (a,b,c):for c in (a,b,c):
      
 
 print(a,b,c)

In [ ]:

print("""
Twinkle, twinkle, little star, 
      How I wonder what you are! 
            Up above the world so high, 
            Like a diamond in the sky. 
Twinkle, twinkle, little star, 
    How I wonder what you are
     """ )
             

2. Write a Python program to get the Python version you are using.

In [ ]:
# To check your Python verson inside a script use:
import sys
print(sys.version)

3. Write a Python program to display the current date and time.

In [ ]:
##3
from datetime import date
from datetime import datetime

time=datetime.now()
day=time.now()
time

In [ ]:
try:
  a=int (input(""))
  b= int ( input(" "))
  c=a/b
except Exception as args:
  print(" error ")

else:
  print(c)
finally:
  print(" it will print")

In [ ]:
class AgeException(Exception):

 def __init__(self,age):
   self.age=age

 def __str__(self):
   return " undergoing age"+str(self.age)


In [ ]:
age= int (input(""))
try:
  if age<18:
    raise AgeException(age)
except AgeException as args:
    print("error",args)
else:
  print(" ready to vote")

In [ ]:
class industryexception(Exception):
  def __init__(self,name):
    self.name=name
  
  def __str__(self):
    return " the name is empty"+self.name

    



In [ ]:
name=input(" entr the name")
try:
  if name == '':
    raise industryexception(name)
except industryexception as args: 
   print("error",args)
else:
    print("name:",name) 

In [ ]:
class iso(Exception):

  def __init__(self,number):
     self.number=number
  
  def __str__(self):
    return " error in name"+str(self.number)

In [ ]:
number= int (input(" enter the number"))
try:
 if number< 10:
  raise iso(number)
except iso as args:
    print(" printer ",args)
else:
  print(" number",number)


In [ ]:
class a:
  def parent(self):
    print(" i am a parent")
  
  def ninja(self):
    print(" ninja from parent")

class b:
  def child():
    print(" i am achild")  

  def ninja(self):
    print(" ninja from child")
class c(b,a):
  def grandchild():
    print(" hi i am grand chilf")

In [ ]:
c1=c
c1.ninja(self="sa")

In [ ]:
from abc import ABC 
class a(ABC):
  def dk():
    print(" abstact method on")


a1=a
a.dk()

In [ ]:
s

In [ ]:
a= input()
row=0
for i in range(len(a),0,-1):
  row+=1
  print(a[:-i],"row",row)

In [ ]:
name=[["rahul","bagal"],["jkumar",232]]
name[1]
for i in name[0]:


 

 print(i)


In [ ]:
animals=["jonny_sins","J_ mac","rory_J"]
# animals[0]="rahul" replace
# animals.insert(1,"siddhesh") insert
# animals.sort() sort it will sort in ascending order
# animals.reverse() it will reverse the element
# del animals[2] it will delete the element
# animals.append("deepak") it will append the element
animals

In [ ]:
a=[12,[12],[121,"2121"]]

In [ ]:
lista = ('rahul',"bagal","rahul")
# for i in lista:
  # print(i,lista.count(i))
lista[0]

In [ ]:
name="rahul"
list1=[12,12,32.21,12]
tuple1=(121,23232,121)
tuple2=(121,23232,121,323,223,"232","sfnsifsdfg")
len(name)
len(list1)
len(tuple1)
name[:1]
list1[2:3]
tuple1[:1]
name.index("l")
list1.index(12)
name.count("h")
list1.count(12)
tuple1.count(121)
max(tuple1);min(tuple1);sum(list1);sum(tuple1)
r= tuple1+ tuple2
r

In [ ]:
lis1=["ccc","bbb","aa","a"]
# print(lis1.sort(key=len))
lis1

In [ ]:
list2=[[1,12],[21,9],[2,7]]

In [ ]:
def sortbysec(element):
  return element[1]
  

In [ ]:
list2.sort(key=sortbysec)

In [ ]:
list2

In [ ]:
a=["12"]
b = dict(a)
type (b)
b

In [ ]:
d={121,12121,1212122,1212}


In [ ]:
d

In [ ]:
a={1,2,3,4,5,6,7}
b={1,2,3,4,5}
type (a)

In [ ]:
a^b

1. Write a Python program to print the following string in a specific format (see the output). 
Sample String : &quot;Twinkle, twinkle, little star, How I wonder what you are! Up above the world so
high, Like a diamond in the sky. Twinkle, twinkle, little star, How I wonder what you are&quot; Output
:

In [ ]:
print('''Twinkle, twinkle, little star,
            How I wonder what you are!
                  Up above the world so high,
                  Like a diamond in the sky.
Twinkle, twinkle, little star,
    How I wonder what you are''')

2. Write a Python program to get the Python version you are using.

In [ ]:
import sys
print(sys.version)


3. Write a Python program to display the current date and time.
Sample Output :
Current date and time :
2014-07-05 14:34:14

In [ ]:
import datatime
now= datetime.datetime.now()
print(now.strf.time('%y-%m-%d,%h-%m-%s'))

4. Write a Python program which accepts the radius of a circle from the user and compute the
area. 
Sample Output :
r = 1.1
Area = 3.8013271108436504

In [ ]:
from math import pi

radius=float (input())
a=3.141592653589793*radius**2
print(a)
pi

5. Write a Python program which accepts the user&#39;s first and last name and print them in
reverse order with a space between them.

In [ ]:
first=input("enter the first name")
last=input("enter the first name")

print(last[::-1]+""+first[::-1])

6. Write a Python program which accepts a sequence of comma-separated numbers from user
and generate a list and a tuple with those numbers. 
Sample data : 3, 5, 7, 23
Output :
List : [&#39;3&#39;, &#39; 5&#39;, &#39; 7&#39;, &#39; 23&#39;]
Tuple : (&#39;3&#39;, &#39; 5&#39;, &#39; 7&#39;, &#39; 23&#39;)

In [ ]:
lst=[]
while True:
  data=input(" enter data")
  if data=="":
    break

  lst.append(data)
  
print(lst)
print(tuple(lst))

8. Write a Python program to display the first and last colors from the following list. 
color_list = [&quot;Red&quot;,&quot;Green&quot;,&quot;White&quot; ,&quot;Black&quot;]

In [ ]:
color_list = ["Red","Green","White" ,"Black"]
color_list[0]+" "+color_list[3]


10. Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.

In [ ]:

n=int(input())

In [ ]:
import time from system

In [ ]:
n = int (input ("enter the number "))
F0,F1=0,1
for n in range (0,n):
  if n<=1:
    print(n)
  else:
    print(F0,F1)
    F0,F1=F1,F0+F1


9. Write a Python program to display the examination schedule. (extract the date from
exam_st_date). 
exam_st_date = (11, 12, 2014)
Sample Output : The examination will start from : 11 / 12 / 2014

In [ ]:
exam_st_date = (11,12,2014)
print( "The examination will start from : %i / %i / %i"%exam_st_date)

10. Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.

In [ ]:
sum=0
no=int(input("enter no:",))
tno=no
rno=0
while no>0:
   
    d=no%10
    no=no//10
    rno=(rno*10)+d
    
if rno==tno:
  print("armstrong no")
else:
  print("not a armstrong")
   

In [ ]:
fact=1
a = int(input(""))
for a in range(1,a):
 fact+=fact*a
 
 
 
print(fact)

In [ ]:
n = int (input(""))
temp = str(n)
t1= temp+temp
t2= temp+temp+temp 
cons= n+int(t1)+int(t2)
print(cons)

12. Write a Python program to print the calendar of a given month and year.
Note : Use &#39;calendar&#39; module.

In [ ]:
import calendar
a= int(input(" year"))
b= int(input(" month"))
print(calendar.month(a,b))



14. Write a Python program to calculate number of days between two dates.
Sample dates : (2014, 7, 2), (2014, 7, 11)
Expected output : 9 days

In [ ]:
d1=(2014,7,2)
d2=(2014,7,11)
d3=int(d1)
d4=int(d2)
print(d4-d3)

In [ ]:
n = int (input())

if n>17:
  print(n*n)
else:
  a=17-n
  print(a)


17. Write a Python program to test whether a number is within 100 of 1000 or 2000.

In [ ]:
n= int(input())
if abs(1000-n)<=100 or abs(2000-n)<=100:
   print("True")
else:
  print("false")

18. Write a Python program to calculate the sum of three given numbers, if the values are
equal then return three times of their sum.

In [ ]:
n1= int(input())
n2= int(input())
n3= int(input())
n4=n1+n2+n3
if n1==n2==n3:
  print(n4**3)
else:
    print(n4)

19. Write a Python program to get a new string from a given string where &quot;Is&quot; has been added
to the front. If the given string already begins with &quot;Is&quot; then return the string unchanged.

In [ ]:
a=[]
a=input("enter the string")
b=a.split()
if b[0]=="is":
  print(a)
else:
    print("is"+""+a)

22. Write a Python program to count the number 4 in a given list.

In [ ]:
a=[12,2,3,4,4,43]
b=a.count(4)
print("the total times number 4 is ",b)

In [ ]:
x,y= float(input()).split()

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,23,4,4,12],[232,323,12,12,12],[1,21,21,212,21]])

In [ ]:
arr[1][1]

In [ ]:
arr.shape

(3, 5)

In [ ]:
arr.ndim

2

In [ ]:
arr.size

15

In [ ]:
np.linspace(1,10,1)

array([1.])

In [ ]:
a=np.array([21,212,12])

In [ ]:
a

array([ 21, 212,  12])

In [ ]:
a=np.arange(1,20,1)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
a=np.arange(1,21)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
a=a.reshape(4,5)

In [ ]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a[0:4,0:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [ ]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((1,2))

array([[1., 1.]])

In [ ]:
np.empty((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
from numpy import random

In [ ]:
random.randint(10)

2

In [ ]:
random.randint(100,size=(2,5))

array([[75, 51, 77,  1, 50],
       [88, 62, 44, 61, 62]])

In [ ]:
dataset=set()
while True:
  data=random.randint(1,20)
  dataset.add(data)
  if len(dataset)==9:
    break
print(dataset)  
m=np.array(list(dataset)).reshape(3,3)
m


{1, 2, 6, 7, 8, 10, 13, 16, 17}


array([[ 1,  2,  6],
       [ 7,  8, 10],
       [13, 16, 17]])

In [ ]:
random.randint(10)

6

In [ ]:
data={23}
type(data)
data.

set

In [ ]:
import pandas as pd


In [ ]:
d=pd.Series([32323,2323])

In [ ]:
from google.colab import files
uploader=files.download

In [ ]:
a=12.0
b=a%2
b

0.0

In [ ]:
import numpy as np
from numpy import random
a=random.randint(1,11,size=10).reshape(2,5)
a

array([[ 3,  3,  1,  2,  5],
       [ 9, 10, 10,  2,  6]])

In [ ]:
n = int(input())
N=list(map(int,input().split()))
if n!=len(N):
  print("size is not list")
else:
   print(list(reversed(N)))
# n = int(input())
# for i in range(0,n):
#   n0=int(input())
#   N.append(n0)


# print(list(reversed(N)))

  

2
1 2 3
not a list


In [ ]:
# N=int(input())
# k=int(input())
# l=[]
# for i in range(1,N+1):
#   l.append(i)
  

# if k==i:
#   print(1)
# else:
#   print(-1)





N,k=map(int,input().split())
l=[]

l=list(map(int,input().split()))

while N==len(l):
  for i in l:
    pass
    
    
    
    
  if k==i:
   print(1) 
  else:
   print(-1)
  break


2 1
1 2 3


In [ ]:
n=int(input())
count=0
l=0
for i in range(0,1000000):
  count=0
   
if n%i!=0:
  l=len(i)
  print(l,i)
     

4


TypeError: ignored

In [ ]:
d=[]
n= int(input())
r=[]

for i in range(0,n):
  n= int(input())
  d.append(n)
  for j in d:
    for k in d:
      if j>k:
        r.append(j)  
        print(r)    

      


3
1
2
[2]
3
[2, 2]
[2, 2, 3]
[2, 2, 3, 3]


In [ ]:
d=[1,2,3]
# max(d)
r=[]
for i in d:
  if max(d)>=i:
    r.append(i)
    r.reverse()
    print(r)

# d=[1,2,3]
# print(list(reversed(d)))

[1]
[2, 1]
[3, 1, 2]


In [ ]:
n= int(input())
n2=n+n

# for i in range(1,n2+1):
#   if i%2==0:
#     print(i)
# for j in range(1,n2+1):
#   if j%2!=0:
#     b= sum(j)
n= int(input())
n2=n+n
a=[i for i in range(1,n2+1) if i%2==0 ]
b=[j for j in range(1,n2+1) if j%2!=0]
print(sum(b),sum(a))

# print([a,b for i in range(1,n2+1) if i%2==0 for j in range(1,n2+1) if j%2!=0])

1
1 2


In [ ]:
a,b,c=map(int,input().split())

tran=a+b+c

if tran<=180 :
  print("NO")
else:
  print("YES")

30 60 90
YES


In [ ]:
n= int(input())
l=[]

for i in range(1,100000):
  if n%i==0:
    l.append(i)
    print(l,l)

3
[1] 1
[1, 3] 1


In [ ]:
for i in range(int(input())):
  N=int(input())
  rev=0
  while N>0:
    d=N % 10
    N=N // 10
    rev=rev*10+d
    print(rev)

In [ ]:
for _ in range(int(input())):
    p = int(input())
    rev = 0
    while p > 0:
        rev = rev * 10 + N % 10
        p = p // 10
        print(rev)

In [ ]:
a,b,c =map(int,input().split())
sum=a+b+c
area=a*b/2
if sum!=180:
  print("NO")
else:
    print("YES")
# elif sum==180 or area>0:
#   print("YES")

12 212 21
YES


In [ ]:
a,b,c =map(int,input().split())
sum=a+b+c

if sum==180 and a>0 and b>0 and c>0:
  print("YES")
else:
  print("NO")

100 18 42
NO


In [ ]:
a,b,c=map(int,input().split())
sum=a+b+c
area=a*b/2

if sum<180 and area<90:
  print("NO")
if sum==180 and area>0:
  print("YES")

100 18 42


In [ ]:
a,b,c=map(int,input().split())

if a==b==c:

  print(1)
elif (a==b or b!=a and a!=c) or (b==c or c!=a and b!=a) or (c==a or b!=c and 
                                                             b!=a):
  print(2)
elif a!=b and b!=a and c!=a:
  print(3)
else:
  print(-1)

2 4 3
2


In [ ]:
n=int(input())
s=[]
for _ in range(0,n):
  map(int,input().split())



#     12
# insert 0 5
# insert 1 10
# insert 0 6
# printasfdafsdfa
# remove 6
# append 9
# append 1
# sort
# print
# pop
# reverse
# print



2
append
1
print
[1]


In [ ]:
n="hello world"
a=n.split(" ")
N=''.join(a[0])
L=N.capitalize()
M=''.join(a[1])
C=M.capitalize()
L+" "+C

'Hello World'

In [ ]:
# Importing the tensorflow libraries
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
# Data Augmentation + preprocessing
data_gen_train = ImageDataGenerator(rescale=1./255,
                                   rotation_range=30,
                                   vertical_flip=True)
data_gen_test = ImageDataGenerator(rescale=1./255)

In [ ]:
train_X = data_gen_train.flow_from_directory('/content/drive/MyDrive/dataset/single_prediction',
                                            target_size=(128,128),
                                            batch_size=64,
                                            class_mode='binary')
test_X = data_gen_train.flow_from_directory('/content/drive/MyDrive/dataset/test_set',
                                            target_size=(128,128),
                                            batch_size=64,
                                            class_mode='binary')

Found 0 images belonging to 0 classes.
Found 868 images belonging to 1 classes.


In [ ]:
 l=[1,2,3,4,5]
 l2=[21,12,21,12]
# l3=sum(l)
# l3


def sumss(l):
  
  return sum(l)

In [ ]:
print(sumss(l),sum(l2))

15 66


In [ ]:
import pyforest

In [ ]:
dir(pyforest)

['ARIMA',
 'CountVectorizer',
 'ElasticNet',
 'ElasticNetCV',
 'GradientBoostingClassifier',
 'GradientBoostingRegressor',
 'GridSearchCV',
 'Image',
 'KFold',
 'KMeans',
 'LabelEncoder',
 'Lasso',
 'LassoCV',
 'LazyImport',
 'LinearRegression',
 'LogisticRegression',
 'MinMaxScaler',
 'OneHotEncoder',
 'PCA',
 'Path',
 'PolynomialFeatures',
 'Prophet',
 'RandomForestClassifier',
 'RandomForestRegressor',
 'RandomizedSearchCV',
 'Ridge',
 'RidgeCV',
 'RobustScaler',
 'SimpleImputer',
 'SparkContext',
 'StandardScaler',
 'StratifiedKFold',
 'TSNE',
 'TfidfVectorizer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_importable',
 '_imports',
 '_jupyter_labextension_paths',
 '_jupyter_nbextension_paths',
 'active_imports',
 'alt',
 'bokeh',
 'cross_val_score',
 'cv2',
 'dash',
 'dd',
 'dt',
 'fastai',
 'fbprophet',
 'gensim',
 'get_user_symbols',
 'glob',
 'go',
 'import_symbol',
 'imutils',


In [ ]:
name={}
name['rahul']={
    'name':'Rahul',
    'phone':12121
}

name['kela']={
    'name':'kela',
    'age':12
}

import json
json.dumps(name)

'{"rahul": {"name": "Rahul", "phone": 12121}, "kela": {"name": "kela", "age": 12}}'

In [ ]:
f=open("E:\ML\write.txt",'w')
f.write("fucky")
f.close()

In [ ]:
def n():
  yield 1
  yield 2
  yield 3
def __next__(self):
  return self



In [ ]:
x=n()
print(x.next())

AttributeError: ignored

In [ ]:
def simpleGeneratorFun():
    yield 1            
    yield 2            
    yield 3            
   
# Driver code to check above generator function
for value in simpleGeneratorFun(): 
    print(value)

1
2
3


In [ ]:

# A Python program to demonstrate use of 
# generator object with next() 
  
# A generator function
def simpleGeneratorFun():
    yield 1
    yield 2
    yield 3
   
# x is a generator object
x = simpleGeneratorFun()
  
# Iterating over the generator object using next
print(x.next()) # In Python 3, __next__()
print(x.next())
print(x.next())

AttributeError: ignored

In [ ]:
def name(func):
  def kk(*args,**kwargs):
      name='rahul'
      return name
  return kk

@name
def jj(name):
  name='bagal'

  return name


In [ ]:
l=jj("kya")
l

'rahul'

In [ ]:
import time
import threading

def calc_square(numbers):
    print("calculate square numbers")
    for n in numbers:
        time.sleep(1)
        print('square:',n*n)

def calc_cube(numbers):
    print("calculate cube of numbers")
    for n in numbers:
        time.sleep(1)
        print('cube:',n*n*n)

arr = [2,3,8,9]

t = time.time()

t1= threading.Thread(target=calc_square, args=(arr,))
t2= threading.Thread(target=calc_cube, args=(arr,))

t1.start()
t2.start()

t1.join()
t2.join()

print("done in : ",time.time()-t)
print("Hah... I am done with all my work now!")

calculate square numbers
calculate cube of numbers
square: 4
cube: 8
square: 9
cube: 27
square: 64
cube: 512
cube: square: 81
729
done in :  4.009997129440308
Hah... I am done with all my work now!


In [ ]:
def sqrr(lista):
  return ([i*i for i in lista])
def cuba(list):
   return ([i*i*i for i in lista])


In [ ]:
lst=[1,2,3]
lst1=[7,8,9]

r=sqrr(lst)
r1=sqrr(lst1)
print(r,r1)

[1, 4, 9] [49, 64, 81]


In [ ]:
   n = int(input())
   student_marks = {}
   for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
        query_name = input()

print(name,scores)

1
rahul 1 1 1
bagal 1 1 1
rahul [1.0, 1.0, 1.0]


In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import counter
n = int(input())
b=[]

for i in range(0,n):
    s=int(input())
    b.append(s)
    
mean=sum(b)/len(b)   

mode=counter(b)
print(b,mean,mode)

ImportError: ignored

Hackerrank basic python certification answer no 1

In [ ]:
#  this i a point to note in terms of string rotation
a="raHul is a good guy"
b=a[::-1]
# for i in b:
c=[]
k=""
b=b.split(" ")
type(c)
# # b[::-1]
# a=[]
# d=[]
# c=""
for i in b:
  c.append(i[::-1])
  # c=c[::1]   this is a point to note in terms of list
  k=" ".join(c)          
  #  c=b.append(i)
#   d=a.append(i)

# d


# a
c
k.title()

'Guy Good A Is Rahul'

In [ ]:
b="hi there how  are you "
c=""
f=""
for i in b:
  c=b[::-1]
  for i in c:
    f=c[::-1]
  
print(f)

hi there how  are you 


In [ ]:

from collections import Counter
e=[{"rahul":"new","lolo":['rash',"koko"],"lotu":"fotu"}]
print(Counter(e))



TypeError: ignored

In [ ]:
# from collections import Counter
d={'rahul':['rahul','dasd',"dasds","rahul"]}
d['koko']='awdsa'
d[90]='kokoko'
d["pogo"]="asdasd","sas"

d["pppp"]="loasun,poiuy"
# print(Counter.most_common(d))
print(d['pppp'][0:])
print(d)

loasun,poiuy
{'rahul': ['rahul', 'dasd', 'dasds', 'rahul'], 'koko': 'awdsa', 90: 'kokoko', 'pogo': ('asdasd', 'sas'), 'pppp': 'loasun,poiuy'}


In [ ]:
f={"ppp":"klkl","poiu":"jnkj"}
for i in f.keys():
  key=f[i]
  # values=f.values()
  print(i,key)

  b=[]
  b.

ppp klkl
poiu jnkj


In [ ]:
# if __name__ == '__main__':
a=[]
m=[]
contains_digit=False
for _ in range(int(input())):
  name = input()
  score = float(input())
  a.append(name)
  a.append(score)
        
# m=[x for x in a if a.isdigit()]

print(a)
s=str(a)
d=s.split(",")
print(d)
for i in d:
  if i.isdigit():
    contains_digit=True
    if contains_digit==True:
      m.append(i)
  
m

# print(md23)
# m.sort()
# m.reverse()
# m[1]
        
        
        


In [ ]:
a={['inio',11]:('11',11)}

In [ ]:
a=[]
b=int(input())
c=a.append(b)
print(c,type(c))

23
None <class 'NoneType'>


In [ ]:
line="my name is rahul"


In [ ]:
s=input()
s=s.split(" ")
d=list(s)
l=""
c=[] 
for i in d:
  c.append(i.capitalize())
  l=",".join(c)
    
  
  
# r=s.capitalize()
print(l)

hi there my name is rahul
Hi,There,My,Name,Is,Rahul


In [ ]:
def print_full_name(first, last):

    return f" hello {first} + {last} + ! You just delved into python."
    
    # Write your code here






In [ ]:
df=print_full_name(input(),input())d
df

rahu
dasd


' hello {first} + {last} + ! You just delved into python.'

In [ ]:
from functools import reduce

# name,age=map(int,input().split())
a=[23,32,23]
data=lambda x,y:x*y
nums=reduce(data,a)
print(nums)

16928


In [ ]:
from decimal import Decimal

n = int(input())
student_marks = {}
val=[] 
for _ in range(0,n):
  name, *line = input().split()
  scores = list(map(float, line))
  student_marks[name] = scores
  
query_name = input()
# if query_name==student_marks.keys():
#    values = query_name.values()
#    print(values)
for k in student_marks.keys():
   if k==query_name:
    s=student_marks[k]
    # print(round(sum(s)/len(s),3))
    r=Decimal(sum(s)/3)
    print(round(r,2)) 
#   r=sum(val)/3
# print(val)
# print(student_marks.keys,query_name)
# print(r)
# Krishna 67 68 69
# Arjun 70 98 63
# Malika 52 56 60


3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


In [ ]:

s=set()

n=int(input())
for i in range(0,n):
   n=input()
   s.add(n)
    
print(len(s))
    

7
UK
China
USA
France
New Zealand
UK
France
5 {'New Zealand', 'UK', 'China', 'USA', 'France'}


In [ ]:
n = int(input())
integer_list = map(int, input().split())
print(hash(tuple(integer_list)))
    

2
1 2
3713081631934410656


In [ ]:
# enter the montly salary
# enter the number of expense 
# enter the amount to deduce 
# amount remain after deducing 




def bdg(salary,expenses):
  print(salary)
    for i in range(0,expenses):
      deduce=[]
      amt=float(input())
      deduce.append(amt)
      remains=sum(deduce)-(salary)
      return remains




In [ ]:
start=bdg(122,32)
start

12


-110.0

In [ ]:
import numpy as np
from collections import Counter
l=[]
a=[]
subjects=["Ml","CL","BD","JAVA","python","sql","linux","powerbi"]
for i in range(0,7):
  l=np.random.choice(subjects)
  a.append(l)


  
  
print(a)
print(Counter(a))

['BD', 'Ml', 'JAVA', 'linux', 'linux', 'sql', 'linux']
Counter({'linux': 3, 'BD': 1, 'Ml': 1, 'JAVA': 1, 'sql': 1})


In [ ]:
# 1-py,ML,ML,sql,java,linux,bd,linux
choice=["linux","Ml"]
start=np.random.choice(choice)
start

'Ml'

In [ ]:
i = 1
b=7
while True:
  if i%b!=0:
    break
    print(i) 
    i += 1

In [ ]:
# ['ab','cd'  i.upper() print(x) for i in x:]

a=['ab','cd']
for i in a:
  i.upper()
  print(i.upper())

AB
CD


Q.3)What is the output of the following?
x = "abcdef" i = "a" while i in x: print('i', end = " ")
a) no output b) i i i i i i ... c) a a a a a a ... d) a b c d e f

In [ ]:
# x="abcdef"
# i="a"
# while i in x:
#   print('i',end=" ")

# if None:
#   print("hello")
# while 4==4:
#   print('4')

Streaming output truncated to the last 5000 lines.
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4

KeyboardInterrupt: ignored

In [ ]:
for char in 'PYTHON STRING':
  if char=='':
    break
    
print(char,end='')
    # if char=='O':
    #   continue

G

In [ ]:
import math
print([str(round(math.pi))for i in range(1,6)])

['3', '3', '3', '3', '3']


In [ ]:
t=32.00
print([round((x-32)*5/9) for x in t])

TypeError: ignored

In [ ]:
l=[1,2,3,4,5]
print(l*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
values= [[3, 4, 5, 1], [33, 6, 1, 0.4]]
v = values[0][0]
for lst in values:
  for element in lst:
    if v > element:
      v = element 
      
      
print(v)

0.4


In [ ]:
a=list((45,)*4)
print((45)*4)
print(a)

180
[45, 45, 45, 45]


In [ ]:
A = [[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]
[A[i][len(A)-1-i] for i in range(len(A))

3


In [ ]:
# x=['ab', 'cd'] 
# for i in x:
#   x.append(i.upper())
  
# print(x)

i=1
while True:
  if i%3 == 0:
    break

 
print(i)
i+=1

In [ ]:
from collections import Counter
b={'a':12,'b':23,'c':34,'a':12}
c=[]
for i in b.keys():
  c.append(i)
print(Counter(c))
print(type(b))

Counter({'a': 1, 'b': 1, 'c': 1})
<class 'dict'>


In [6]:
a=[1,2,3,4,5]
for i in a:
  if i%2==0:
    print(i,"even")
  else:
    print(i,"odd")

1 odd
2 even
3 odd
4 even
5 odd


In [31]:
# a={"r":1}
# aa={"t":3}
# b=a.update(aa)
# print(a)
# a=[12,32]
# b=[12,23]


# print("rahul"*4)

class intro:
  def name(self):
    self.name=input()
    print(self.name)
  def surname(self):
    print("bagal")
  def fullname(self):
    print()



In [32]:
h=intro()
h.name()
# h.surname()

rahul
rahul


In [65]:
def salary():
  salary=int(input("what is your salary"))
  expense=int(input("how many number of expense"))
  for i in range(0,expense):
    spendedon=input("the amount which i spended")
    deduce_amt=int(input())
    salary-=deduce_amt
    rem_salary=salary
    print(rem_salary)


  

In [67]:
d=salary()
d

what is your salary500
how many number of expense3
the amount which i spended34
34
466
the amount which i spendedliqor
90
376
the amount which i spendedstocks
90
286
